### ISSUE TITLE
Incompatibility with fastclick?

### ISSUE THREAD

**Issue by FredUK** [cibernox/ember-power-select#248] opened 2016-01-20 11:11 UTC
Hi, great plugin first of all.

I have noticed an issue in combination with the fastclick plugin in a mobile browser (iPad). 

Fastclick (https://github.com/ember-mobile/ember-cli-fastclick)  is "a polyfill to remove click delays (300ms) on browsers with touch UIs" which make webapps in mobile browsers much more responsive and feeling more like a native app however power-select will not open at all when fastclick is running on an ember project. Can you confirm if this is a bug and if/or you would be willing to take a look at it?

Thanks a lot for the great work with this plugin.

**Comment by cibernox** [comment] 2016-01-20 11:19
I never tried it in conjunction with fastclick, mainly because in android and the latest ios fastclick is not required anymore, but I'll check why.

The latest version of this component uses mousedown/mouseup events to open/select. I'm surprised that fastclick messes with those. Are you in 0.8.0?

**Comment by scientiacloud** [comment] 2016-01-20 12:04
I was running 0.7.1 but I have updated it to 0.8 recently and still displays the same issue. 
I noticed that the only way to open the drop down is to click and hold it for one second and then release. But simple tapping does not work. I'm trying it on ios 9.1 by the way.

**Comment by FredUK** [comment] 2016-01-20 12:04
I was running 0.7.1 but I have updated it to 0.8 recently and still displays the same issue. 
I noticed that the only way to open the drop down is to click and hold it for one second and then release. But simple tapping does not work. I'm trying it on ios 9.1 by the way.

**Comment by FredUK** [comment] 2016-01-21 14:37
Just wanted to add that it is possible to replicate this issue in Chrome if you just toggle Device Mode under the Developer Tools and pick a device which is touch enabled.

**Comment by jeremytm** [comment] 2016-02-18 05:44
+1
Fastclick is still needed on iOS

**Comment by ricky1981** [comment] 2016-02-21 21:59
A proper fix would be great but as a workaround, you can just use the "needsclick" class (this disables fastclick). So something like this inside your power select tags:

`<span class="needsclick">{{option.name}}</span>`

Obviously if you are using something more complicated than a text string then you could apply the class to a div and it should still work.

**Comment by cibernox** [comment] 2016-02-22 11:23
@ricky1981 would be possible to just add that class to the entire component? If so, 
`{{#power-select ... triggerClass="needsclick" dropdownClass="needsclick" as |opt|}}...` could work.

**Comment by ricky1981** [comment] 2016-02-22 20:30
Thanks @cibernox , I'll give that a try later today.

Awesome addon by the way!

**Comment by ricky1981** [comment] 2016-02-23 02:08
Working a treat!

**Comment by daniel-de-wit** [comment] 2016-02-25 12:45
@ricky1981 Did you manage to find a working solution?

**Comment by cibernox** [comment] 2016-02-25 16:50
I've tried to reproduce this on the latest version (0.9.0-beta.6) and worked fine with fastclick.
I'd say that fastclick is not speeding the interactions and the 300ms delay is still there but it does work.

Can anyone confirm?

**Comment by ricky1981** [comment] 2016-02-25 18:24
Still not working for me, quite easy to replicate, just use Chrome and toggle to Device Mode and it stops working. Disable Device Mode and it works fine. Also tested on iOS 9.2 and got the same issue.

**Comment by cibernox** [comment] 2016-02-25 19:26
I pushed the branch where I tried to reproduce it: https://github.com/cibernox/ember-power-select/tree/try_to_reproduce_fastclick_bug

Pull the repo, checkout the `try_to_reproduce_fastclick_bug` and `ember s`.

I tried in device mode, and in real phones, both android and iphone. Does it fail?

**Comment by daniel-de-wit** [comment] 2016-03-01 10:56
I created a fresh Ember project and added FastClick and Ember Power Select. And they worked, like you said.

When I copied my package.json and bower.json contents over to the freshly made ember app it no longer worked. However I do seem te be able to open de dropdown when tapping on the outer corner it.
Here is a small recording of what the problem looks like:


![ember-power-select-fastclick-issue-demonstration](https://cloud.githubusercontent.com/assets/3015394/13425004/6f09fa1c-dfa4-11e5-8291-776d9f480848.gif)


I will continue checking what other package is causing the conflict. Might take a while since my app is huge. Keep you posted!

**Comment by cibernox** [comment] 2016-03-08 10:58
For those with fastclick issues, can you check if this branch fixes the behaviour?
https://github.com/cibernox/ember-power-select/tree/depend_on_experimental_branch_of_ember_basic_dropdown_with_touch_support

I think that it should at least fix the open/close problem, but have only tested it in an android device and one emulator.

**Comment by ricky1981** [comment] 2016-03-08 19:23
In my testing, iOS 9.3 removes the need for fastclick so I've decided to choose power-select over fastclick as I think it is more useful.

This link might be useful as it explains browser support for removing the 300ms delay - http://patrickhlauke.github.io/touch/tests/results/#suppressing-300ms-delay

**Comment by cibernox** [comment] 2016-03-08 20:20
@ricky1981 I'm going to continue adding native touch support anyway because sometimes webs have to be scalable. But yes, that 9.3 features arrives 2 years later. When will 9.3 be mainstream?

**Comment by ricky1981** [comment] 2016-03-08 20:31
@cibernox There's no confirmed date yet but it's up to public beta version 5 so I'd guess we're looking at a maximum of 2 months.

**Comment by daniel-de-wit** [comment] 2016-03-08 21:40
Tested the branch on:
- iPad Mini Chrome
- iPad Mini Safari
- iPhone Chrome
- iPhone Safari

- OSX Chrome Device modes

Opening and closing of the dropdown works :tada:

Thank you for taking the time to support compatibility with FastClick

**Comment by daniel-de-wit** [comment] 2016-03-11 10:07
Should I make a new issue for not being able to select an option? Basically the dropdown now opens and closes ( which is great ) but users are still not being able to select any option making the add-on unusable still.

**Comment by cibernox** [comment] 2016-03-11 10:12
When I tried it selected options for me. I'll check it today. Reopening.

**Comment by cibernox** [comment] 2016-03-17 14:59
@daniel-de-wit I've finally implemented two long awaited features, event delegation and touch events in the options of the list.

This should make it compatible with fastclick finally.

**Comment by daniel-de-wit** [comment] 2016-03-22 11:13
I've just tried with v0.10.0-beta.3 on a couple of mobile devices and your solution works great.

I believe we can close this issue :tada: 

Thanks for all your hard work on this :+1:

**Comment by cibernox** [comment] 2016-03-22 11:16
Great!

**Closed by cibernox** 2016-03-22 11:16 UTC
Labels: help wanted
