### ISSUE TITLE
Unable to use extension with Chrome extension Virtual Keyboard (xontab.com)

### ISSUE THREAD

**Issue by alankila** [cibernox/ember-power-select#751] opened 2016-12-06 21:25 UTC
I am using the extension called Virtual Keyboard on Linux-based system to create a keyboard for touch-screen systems on Linux-based appliance product. Normally, on-screen keyboards are the operating system's responsibility, but in case of Linux desktop, they come with various shortcomings such as not triggering automatically, and the problems have made an extension-based keyboard quite appealing in comparison.

The extension creates a JavaScript layer on the screen showing an image of keyboard, and binds to click events on the buttons. One issue that I am now having is that ember-power-select closes the search mode whenever clicking a key on the virtual keyboard. To workaround this, I override the onClose hook to return false as long as the virtual keyboard is still kept open by user.

This allowed me to type into the search field, but unfortunately this does not trigger the actual search for the values within the ember-power-select. It seems that despite the input value changes, the changes are simply not observed by the power-select component. I eventually worked around the problem manually by writing what amounts to some absurdly terrible code:

```
  onclose(publicApi: any, e: Event) {
    let vkce = Ember.$("#virtualKeyboardChromeExtension");
    /* Keyboard not open, we can ignore this */
    if (vkce.attr("_state") !== "open") {
      return true;
    }
    /* Check if the click occurred within virtual keyboard */
    let node = Ember.$(e.target);
    while (node.length) {
      if (node.attr("id") === "virtualKeyboardChromeExtension") {
        Ember.run.later(() => {
          let text = Ember.$("div.ember-power-select-search input").val();
          publicApi.actions.search(text);
        }, 100);
        return false;
      }
      node = node.parent();
    }
```

**Comment by cibernox** [comment] 2016-12-06 22:12
@alankila do you have a way to reproduce this issue that you can share?

I can see why the component closes when you type on the keyboard, since the component is designed to be closed if you click anywhere outside the select, so this makes sense.

However, I don't see why the search doesn't trigger, since it's bound to the `input` event: https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/before-options.hbs#L10

Can you check if the chrome extension fires input events?

**Comment by alankila** [comment] 2016-12-11 15:54
> Miguel Camba <notifications@github.com> kirjoitti 7.12.2016 kello 0.12:
> 
> @alankila <https://github.com/alankila> do you have a way to reproduce this issue that you can share?
> 
> I can see why the component closes when you type on the keyboard, since the component is designed to be closed if you click anywhere outside the select, so this makes sense.
> 
> However, I don't see why the search doesn't trigger, since it's bound to the input event: https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/before-options.hbs#L10 <https://github.com/cibernox/ember-power-select/blob/master/addon/templates/components/power-select/before-options.hbs#L10>
> Can you check if the chrome extension fires input events?
> 
Hello.

I looked into the source code of the extension. It seems to generate change events only in response to clicks on the keyboard. This extension is one ugly piece of work for sure.

- it puts all sorts of _vk-prefixed attributes into the inputs, adding considerable noise into the DOM

- it has a numeric keyboard mode (which you can’t disable) which allows broken numeric input such as * characters, and it changes every type of input field to text when focused to support this broken concept of numeric input, and it does that even when the extension itself is disabled. One of the better features of Chrome is that it automatically computes numeric input sizes intelligently based on specified min- and max values, and this extension actually breaks the numeric input and the size of the field at the same time.

- it uses the onChange event despite that should fire at end of input, not on all intermediate values of the input

- it fires onChange even when the value hasn’t even changed.

I’m going to throw this one away and implement my own soft keyboard (or integrate something else) as ember component straight into the page. All I need to integrate this properly is to keep the onClose hook working, which I’m sure I can do.

Antti

**Comment by cibernox** [comment] 2016-12-11 16:55
Yeah, it seems pretty dodgy. I'll close this for now.

**Closed by cibernox** 2016-12-11 16:55 UTC
