### ISSUE TITLE
Versions error in  @embroider/util package

### ISSUE THREAD

**Issue by usamahamed** [cibernox/ember-power-select#1499] opened 2022-01-25 14:15 UTC
Currently, i updated the ember-power-select to version `5.0.3` and I also have @embroider/util version `0.47.2` but my test cases fail because of the Dependency Linting error in the package `ember-element-helper` because it uses the old version of `@embroider/util ` 

see: 
<img width="788" alt="Screenshot 2022-01-25 at 15 14 49" src="https://user-images.githubusercontent.com/23267284/150993230-9986ce2c-4563-43c1-9630-5666616c633b.png">

**Comment by tschoartschi** [comment] 2022-02-08 07:42
Seems like it should be fixed 🙂 for more details [see](https://github.com/cibernox/ember-basic-dropdown/issues/636#issuecomment-1031845917)

**Comment by mkszepp** [comment] 2022-02-10 07:13
@cibernox to fix this issue we need a release of `ember-power-select`, which contains `@embroider/util` v1.0 (is already merged merged https://github.com/cibernox/ember-power-select/pull/1500)

**Comment by jamescdavis** [comment] 2022-02-10 14:56
+1, need a release of https://github.com/cibernox/ember-power-select/compare/v5.0.3...master 🙂

**Comment by cibernox** [comment] 2022-02-19 21:23
I just published 5.0.4, hopefully this is solved now. Please reopen if there are remaining issues.

**Closed by cibernox** 2022-02-19 21:23 UTC

**Comment by usamahamed** [comment] 2022-02-21 10:30
@cibernox I think there is something missing to be updated because `ember-basic-dropdown` still using `@embroider/util` version `0.47.2`  and ` ember-element-helper` still using version `0.41.0` see: 

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/23267284/154937356-7e54d096-9100-45de-ae45-96df6d47a138.png">

**Comment by mkszepp** [comment] 2022-02-21 10:35
@usamahamed `ember-basic-dropdown@4.0.3` or greater are already using `@embroider/util@1.0.0` see https://github.com/cibernox/ember-basic-dropdown/pull/643

**Comment by usamahamed** [comment] 2022-02-21 11:14
@mkszepp Thanks for the hint 👍 I will try this

**Comment by tschoartschi** [comment] 2022-02-22 13:36
I run into the same issue 🤔 I tried:

```
rm -rf node_modules package-lock.json
npm i
```

The problem is, that although I use version `"ember-power-select": "5.0.4"` npm always installs `"ember-basic-dropdown": "4.0.2"` instead of `"4.0.4"`. Maybe this has something to do with my setup? 

```
$ npm --version
8.3.1
$ node --version
v16.14.0
$ ember --version
ember-cli: 3.28.2
node: 16.14.0
os: darwin x64
```

OS: macOS Big Sur Version 11.4 (20F71)

**Comment by mkszepp** [comment] 2022-03-04 10:58
@usamahamed i have retested in my repo & a new clean ember project, but i can't reproduce it 🤔.
In my case he has now installed always `"ember-basic-dropdown": "4.0.5"` (which is correct)

Can you share your `package.json` / `package-lock.json`, because the `package.json` from `ember-power-select` looks good with dependency `"^3.1.0 || ^4.0.2"`.

Maybe a other addon brings as dependency this old version.

https://github.com/cibernox/ember-power-select/blob/7f8dc10799c046a028b1e4f58a08a8611f4ce9a1/package.json#L49-L61

**Comment by usamahamed** [comment] 2022-03-17 10:20
@mkszepp Sorry for the late reply 

Here attached my `package.json` and `package-lock.json` `package.json`

npm -v `8.3.1`

node -v `16.14.0`

[att.zip](https://github.com/cibernox/ember-power-select/files/8283797/att.zip)

**Comment by mkszepp** [comment] 2022-03-17 10:47
@usamahamed acutally you have as dependency `ember-basic-dropdown@4.0.5`, so this looks good

![grafik](https://user-images.githubusercontent.com/19845290/158791716-2dd60dca-30f8-4464-b1a8-d711f9f40e1d.png)

the problem is your `devDependencies`: you have added `"ember-power-select": "5.0.3",`

you must replace this with `"ember-power-select": "5.0.4",` or `"ember-power-select": "^5.0.3",`

**Comment by usamahamed** [comment] 2022-03-17 11:33
@mkszepp Many thanks for taking time to investigate the problem, it works for me 🎉 but it opens up another lint issue 😄 

<img width="657" alt="image" src="https://user-images.githubusercontent.com/23267284/158799866-f995ec90-20ad-4e66-9f21-2ffe63f86d46.png">

But this is something related to `ember-cli-mirage`  i will create another issue

**Comment by cah-briangantzler** [comment] 2022-03-17 12:41
You have ember-cli-mirage "2.2.0", need to do the same thing, upgrade to "2.4.0" or list as "^2.2.0" and yarn upgrade. I think the get config may have been updated in 2.3.0
