### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

### ISSUE THREAD

**Issue by tinyweasel** [cibernox/ember-power-select#877] opened 2017-03-29 08:26 UTC
I'm populating these power select multiples with model properties, with existing model data preselected. Most of them work perfectly, but two of the dropdowns throw this error, one of them once, and one of them repeatedly. There doesn't seem to be a problem with the models as they're defined in the same way as the working ones. Has anyone else had this problem, or know how to fix this?

**Comment by tinyweasel** [comment] 2017-03-29 08:28
It also gets the same error on form submission, though the PATCH request does go through successfully.

**Comment by cibernox** [comment] 2017-04-03 10:50
Without a reproduction example is hard to get any idea of what is going on. Also, knowing the versions of EPS and/or ember would help.

**Comment by cibernox** [comment] 2017-04-10 16:06
Without a reproduction I'm going to close this issue, since seems that other project has solved this by updating the version.

**Closed by cibernox** 2017-04-10 16:06 UTC
