### ISSUE TITLE
Unable to pass arbitrary attributes into the trigger

### ISSUE THREAD

**Issue by lolmaus** [cibernox/ember-power-select#1203] opened 2019-02-18 13:43 UTC
I need to pass a `data-test-...` attribute into the trigger. 

Looks like this is impossible to do.

Please pass splattributes (or some pre-Octane equivalent) into the trigger.

Or give the wrapper component a tag.

**Comment by cibernox** [comment] 2019-02-18 13:47
@lolmaus I'm working on updating EmberBasicDropdown and EmberPowerSelect to octane, which includes this ability. I hope I'll have it done in a couple weeks.

**Comment by cibernox** [comment] 2019-02-18 13:50
It is also worth noting that if you use the provided test helpers like `selectChoose` you can give the css part to the trigger **or to a parent of the trigger**. That means that you can also add `data-test-*` to a wapper:

```hbs
<div class="some-div" data-test-foo>
 {{#power-select ...}}{{/power-select}}
</div>
```

```hbs
await selectChoose('data-test-foo', 'Option B');
```

**Comment by jelhan** [comment] 2019-09-10 21:02
HTML attributes are not applied to any element if `@renderInPlace` is `false`, which is the default. Is this by design or just a bug? They are passed down to `<BasicDropdown>`, which only uses them if rendered in place: https://github.com/cibernox/ember-basic-dropdown/blob/8882f3cdd59e3fc2928fc39abf62278812fb308d/addon/templates/components/basic-dropdown.hbs#L33-L37

**Comment by josemarluedke** [comment] 2019-12-28 03:46
I just came across this. I need to pass HTML attributes to the trigger as well. I'm using the octane version 4.0.0-beta.6. 


We could move this line to the trigger: https://github.com/cibernox/ember-power-select/blob/bd3bd9fe2d9ccad5567d7bec09c0c7dae001fcfe/addon/templates/components/power-select.hbs#L13

**Comment by lolmaus** [comment] 2020-01-31 12:44
> @lolmaus I'm working on updating EmberBasicDropdown and EmberPowerSelect to octane, which includes this ability. I hope I'll have it done in a couple weeks.

One year later, has there been any progress? 😇

**Comment by lolmaus** [comment] 2020-02-12 09:32
I have tried @josemarluedke's suggestion in a project and it worked nicely.

Created a PR: https://github.com/cibernox/ember-power-select/pull/1331

**Comment by ybaldus** [comment] 2020-03-26 14:16
@cibernox any chance we are landing this soon? We can't use modifiers on `<PowerSelect>`.

Use case is to change the trigger icon via a custom modifier.

**Comment by cibernox** [comment] 2020-03-26 16:31
I must say that I'm not convinced about this. Ideally I'd the users should be able to choose where they want to apply attributes to, but right now they can't because we're working at the wrong abstraction level. 
The API of the components must be broken down more. While this may make some things easier, it will probably make other that expect attributes to be send to the trigger. I need to expose the API of the component at a lower level:

```hbs
<BasicSelect ...someAttributes as |select|>
  <select.Trigger ...otherOptions></select.Trigger>
  <select.Content></select.Content>
</BasicSelect>
```

**Comment by ybaldus** [comment] 2020-03-26 22:47
Yes, I think you have a point there, but for this to work: 
`<BasicSelect ...someAttributes />`
We will need an option to define a tag name for `<BasicSelect />`. At the moment we only have renderInPlace for that which will use another calculate position function.

**Comment by lolmaus** [comment] 2020-03-29 08:11
@cibernox In the mental model of any user who's not got elbow deep into the `ember-power-select` source, is different from yours. What new Power Select users see is a component:

```
<PowerSelect>
</PowerSelect>
```

They don't see a "trigger", a "content", a "wormhole", whatever. They see a component called `PowerSelect`.

And *every* new user has an expectation that applying attributes on it will work. This is how every component in the Ember ecosystem works, and Power Select is probably the only one that breaks the expectation — and does so without warning. The behavior of dropping attributes/splattributes/modifiers is not documented, so you need to research its source to learn that `<PowerSelect>` is tagless and does not pass splattributes to the rendered component (Trigger).

Why does it not pass attributes to the rendered component? Because ideally you should be able to apply splattributes to the Content component, so you get nothing.

Yes, trigger and content elements customization are also legit cases, but passing attributes to the Power Select component itself (what you call Trigger under the hood) is a much, *much* more common necessity.

I don't see how a feature request for customizing the Content prevents from solving a source of pain for many Power Select users.

***

I'm speculating here, but I believe that every `ember-test-selectors` user who needed to acceptance-test a Power Select has spend at least two hours on this problem. And `ember-test-selectors` [has](https://emberobserver.com/addons/ember-test-selectors) ~250 000 installs per month, so that's a lot of hours of frustration.

And `ember-tests-selectors` is just *one* of many reasons why you need attributes/modifiers on a Power Select. There are many more.

***

Also please note that there is a RFC in progress called "Splat Areas": https://github.com/emberjs/rfcs/issues/517. It aims to solve the same problem that you pointed out, but in a more general way. It's in an early stage, but still I believe it makes little sense to undertake a custom solution when a general solution is on the way. We should rather join forces over the RFC.

Please see if the RFC issue in its current way satisfies your needs. If it doesn't, please express what it's lacking and why, and suggest an alternative implementation if you can. If it does satisfy you needs, please encourage to promote it into a PR.

**Comment by lolmaus** [comment] 2020-03-29 08:16
The Splat Areas RFC discussion has [argumentation](https://github.com/emberjs/rfcs/issues/517#issuecomment-515553066) for why yielding sub-components is not a great solution, compared to the proposed one.

TL/DR: I believe we should merge https://github.com/cibernox/ember-power-select/pull/1331 now, relieving a big pain point for many Power Select users.

Then we can focus on getting https://github.com/emberjs/rfcs/issues/517 accepted, and when it's implemented, leverage it in Power Select.

**Comment by rwwagner90** [comment] 2020-04-13 16:51
This issue is blocking ember-bootstrap-power-select as well https://github.com/kaliber5/ember-bootstrap-power-select/issues/93. Anything I can do to help fix things? If the PR @lolmaus opened works, I would love if we could get it merged!

**Closed** 2021-06-10 13:50 UTC

**Comment by lougreenwood** [comment] 2021-09-07 09:59
Can we re-open this? It's still not possible to pass args to the trigger if `renderInPlace` is `false`.
