### ISSUE TITLE
Issue using Ember Data with ember-power-select v4.1.7 for custom searches

### ISSUE THREAD

**Issue by waihon** [cibernox/ember-power-select#1482] opened 2021-11-20 15:05 UTC
I'm learning to use `ember-power-select` addon to perform custom searches. 

Here's the component invocation:
```
<PowerSelect
  @selected={{this.selectedAuthor}}
  @searchEnabled={{true}}
  @search={{this.searchAuthor}}
  @onChange={{this.selectAuthor}}
  as |author|
>
  {{author.last}}, {{author.first}}
</PowerSelect>
```

My project uses Ember Data. So my first implementation of the search function is as follows:
```
@action
searchAuthor(query) {
  return this.store.query('author', { filter: { query } });
}
```

That seemed to work initially but I then noticed an issue: the "Loading options..." kept on displaying even though all the expected search results have come out. I  navigated to the Network tab and noticed continuous calls to the API server.

I revised the search function by adding `async` and `await`:
```
@action
async searchAuthor(query) {
  let authors = await this.store.query('author', {
     filter: { query }
  });
  return authors.toArray();
}
```

The issue with "Loading options..." and continuous calls to the API server still happened.

I revised the search function to use `fetch`:
```
@action
async searchAuthor(query) {
  let host = ENV.apiHost ?? '';
  let url = `${host}/authors?filter[query]=${query}`;
  let response = await fetch(url);
  let json = await response.json();
  return json.data;
}
```

... and the component invocation as follows:
```
<PowerSelect
  {{!-- no changes --}}
>
  {{author.attributes.last}}, {{author.attributes.first}}
</PowerSelect>
```

This time it worked, i.e. the "Loading options..." disappeared after the all the expected search results have come out, and there were no continuous calls to API server.

According to https://guides.emberjs.com/release/models/finding-records/#toc_querying-for-multiple-records, `query()` returns a PromiseArray in the same way as `findAll`. So I thought it would work with the addon.

May I know how to make `ember-poser-select` to work with Ember Data,  `this.store.query()` in particular?

**Comment by waihon** [comment] 2021-11-20 16:46
Regarding the above issue (ember-power-select addon with Ember Data), I tried to downgrade the addon's version and found that the issue doesn't happen for 4.0.0 through 4.0.6. It seems to happen starting with 4.1.0.

**Comment by waihon** [comment] 2021-11-21 08:44
Here's a recording of the issue for better understanding.
https://user-images.githubusercontent.com/1195433/142755589-937e3240-e2f5-4404-aec3-03b1e0586706.mov

**Comment by waihon** [comment] 2021-11-21 09:07
I checked Ember Data's _query() method and noticed it has changes since Ember 3.22.0.

Here's the _query() method of 3.21.0: https://github.com/emberjs/data/blob/v3.21.0/packages/store/addon/-private/system/store/finders.js#L359
Here's the _query() method of 3.22.0: https://github.com/emberjs/data/blob/v3.22.0/packages/store/addon/-private/system/store/finders.js#L359

I tested in my local machine with Node v12.22.2, the ember-power-select 4.1.7 works with Ember Data's `this.store.query()` up to 3.21.0 but doesn't work with 3.22.0 onwards.

Could the project team please look into this issue and resolve it so that this addon could work with recent versions of Ember, i.e. 3.22.0 onwards?

**Comment by waihon** [comment] 2021-11-26 08:32
Though the version of `seatchAuthor` using `fetch` mentioned above has prevented that issue of continuously calling the API server, it doesn't work well with other part of the application.

Other part of the app expects to receive an array of Author objects instead of an array of JSON data items.

Besides, using Ember 3.21 is not a long-term solution as well.

So I'm still looking for a long-term solution to have ember-power-select works with the latest version of Ember.js and which returns an array of Author objects in this case, and not an array of JSON data items.

**Comment by cibernox** [comment] 2021-11-28 22:07
I also thought that the returned object from `store.query` was a promise-like object, and it was at some point. If that changed in 3.22 I didn't notice. I'm going to try to create a reproduction. Maybe you have some small reproduction you can share?

I have a couple question:
- Does calling `store.query` in any other action work as expected and not end up in an infinite loop of requests?
- If that works, can you put a debugger and try to figure out what's making the search fire? The only think I can think that would make the search fire over and over again is the input loosing and gaining focus all the time. If that was the cause I can think in a way of preventing it by checking the the search term is the same of the one from the last search (this makes the assumption that the results don't change too often).
- Did you try to wrap the result of of `store.query` in a promise with `Promise.resolve(this.store.query(...))`. Just to rule out a few things.

**Comment by SumanHansada** [comment] 2021-11-29 10:17
Hi 👋🏻 @cibernox! I was also going through the issue of @waihon. Found that using async await with this.store.query results in some sort of infinite loop. I tried everything, Promise.Resolve, awaiting, debouncing for milliseconds as well.
But works perfectly fine with ember-concurrency task.
Here is the repository with reproduction - https://github.com/SumanHansada/power-select-demo
in the file components\dropdown.js

**Comment by cibernox** [comment] 2021-11-29 13:57
@SumanHansada great, I'll try to debug what's going on tonight!

**Comment by waihon** [comment] 2021-12-03 02:13
Hi @cibernox, may I know how's the debugging come along?

**Comment by mayatron** [comment] 2021-12-12 22:26
I ran into this issue recently as well. Thanks @SumanHansada for the suggestion to use `ember-concurrency`. That worked for me, but _only_ when I was using a debounce within the task.

I didn't have a chance to dig into this much, but I suspect that the `{{did-update}}` modifier below is getting fired repeatedly, in an infinite loop.

https://github.com/cibernox/ember-power-select/blob/a8cd2f95f24963f33b89e83ed30ca6c1f907c054/addon/components/power-select.hbs#L36

**Comment by mayatron** [comment] 2021-12-14 22:29
I suspect this issue could be fixed by updating `@ember/render-modifiers` `2.0.1` or `2.0.2` released today, which includes a fix for this issue: https://github.com/emberjs/ember-render-modifiers/pull/54

**Comment by cibernox** [comment] 2021-12-14 23:37
@mayatron that give me some hope, I couldn't find why this was being invoked on a loop. I published 5.0.3 with the updated dependency.  @waihon can you check if that new version still presents this problem?

**Comment by cibernox** [comment] 2021-12-14 23:38
Ooops, I didn't intend to close this.

**Comment by waihon** [comment] 2021-12-21 09:43
@cibernox, thank you for releasing a new version (5.0.3)! It no longer presents the problem. 

@mayatron, thank you for suggesting a solution for the issue!

**Comment by cibernox** [comment] 2021-12-22 16:04
Fantastic! Glad the bug was somewhere else because I couldn't find any evident bug in this addon's code. Thanks!

**Closed by cibernox** 2021-12-22 16:04 UTC
