### ISSUE TITLE
Support for new item creation

### ISSUE THREAD

**Issue by taurusismysign** [cibernox/ember-power-select#89] opened 2015-11-02 12:56 UTC
Ability for control to accept a "new item" (especially in multi mode or search mode) so that the UI takes input from the user, and later triggers events which can help creation of the input which user provided.

**Comment by cibernox** [comment] 2015-11-02 13:34
Yes, it's coming soon, probably this week.

This is a duplicate of #72, so I will close to keep track of missing features in only one place

**Closed by cibernox** 2015-11-02 13:34 UTC
