### ISSUE TITLE
Auto-advance between dropdowns and keyboard commands broken

### ISSUE THREAD

**Issue by CAH-MaggieRoss** [cibernox/ember-power-select#320] opened 2016-02-16 16:37 UTC
To Reproduce:

- Go to http://www.ember-power-select.com/docs/the-search
- Select an option on the **default behavior** dropdown
- Tab to the **Customize the search field** dropdown
- Push down arrow on keyboard and Return to select an option
- Push down arrow again
- A second instance of the dropdown opens in upper left corner and  **default behavior** dropdown now shows `[object Object]`
- Typing will appear in first dropdown, but filter the second dropdown; filtering and/or arrow selecting and hitting Return will not change the results in any dropdown

![screen shot 2016-02-16 at 11 29 10](https://cloud.githubusercontent.com/assets/5324189/13082902/968a8d36-d4a0-11e5-9169-6a741d066d60.png)

This is very similar to an issue it's causing in our app where when you select a result in the first dropdown it auto-advances to the second dropdown, and using the down arrow re-draws the second dropdown under the first field as well as opening the first dropdown in the upper right corner. 

![screen shot 2016-02-16 at 11 31 20](https://cloud.githubusercontent.com/assets/5324189/13082990/103a9ad6-d4a1-11e5-99a0-949ccf71ae98.png)

In our case, however, using the arrows again does move the selection in the second dropdown and hitting Return will close it and show the correct selection--but not close the re-opened first dropdown.

**Comment by cibernox** [comment] 2016-02-16 17:17
I think that the bug you describe is not related. 

The problem in the page was that all selects in that page were bound to the same property in the controller, and since some of the options were objects and other strings, some select broke when selecting one object of the wrong type.

Are you using the latest version? I remember fixing one error that had to do with how the focus worked, causing component to be opened but the focus remained in the previous component. That might be the cause of your issue.

**Comment by CAH-MaggieRoss** [comment] 2016-02-16 19:25
I had just moved up to v0.9.0-beta.3 from v0.8.6; I've just started stepping back through tags to see where it started being an issue, but haven't hit one yet as of v0.9.0-beta.0.

Also, still getting the issue on the demo page:
![screen shot 2016-02-16 at 14 24 33](https://cloud.githubusercontent.com/assets/5324189/13088158/13333b9a-d4b9-11e5-8a12-32f7877357e5.png)

**Comment by cibernox** [comment] 2016-02-16 19:34
I'm having some problems with the deployment, so you're still seeing the old version in www.ember-power-select.com. If you clone the repo and run `ember s` you should see that it's fixed.

So, I understand that updating to 0.8.0-beta.3 didn't fix it in your app. I need to investigate it then.

**Comment by CAH-MaggieRoss** [comment] 2016-02-16 19:41
As of right now, I've checked all tags 0.7.0-beta.1 through current, and we're having the issue in all of them. 

Also, while Return will select an option and advance to the next dropdown, trying to Tab with an option highlighted (which is standard on most web dropdowns) will close the dropdown and move to the next, but will not select the highlighted option and open the next dropdown as would be expected.

**Comment by cibernox** [comment] 2016-02-16 19:45
About the tab, I took [selectize.js](http://selectize.github.io/selectize.js/), [select2.js](http://selectize.github.io/selectize.js/) and the native `<select>` tag for inspiration for the default behaviour of this select, and none of them selects the highlighted option when the user uses the TAB key.

**Comment by CAH-MaggieRoss** [comment] 2016-02-16 19:53
Gotcha. I was thinking of the dropdowns that show up under input fields like for Chrome's autocomplete, not the selects. Whoops.

**Comment by CAH-MaggieRoss** [comment] 2016-02-17 14:46
Discovered I was having an issue with npm not cleaning the cache properly on the install, retested tags after doing so and we're only seeing the issue in 0.9.0-beta.1 through current--0.8.6 and back work fine. Which is good for our ability to roll back, but also sad since that line-height fix is in 0.9.0-beta.1.

**Comment by cibernox** [comment] 2016-02-17 14:51
The deploy seems to be fixed. Can you reproduce this error again in http://www.ember-power-select.com/docs/the-search ?

**Comment by CAH-MaggieRoss** [comment] 2016-02-17 16:18
Can't seem to reproduce there, but the beta.5 is still causing the same issue in our app I showed above--went straight from 0.8.6 where it doesn't happen to 0.9.0-beta.5.

**Comment by cibernox** [comment] 2016-02-17 16:21
Ok, at least this confirms my suspect that the bug you have and the error in the docs weren't related. Is there any error in the console? Are you customizing any part of the select?

**Comment by cah-briangantzler** [comment] 2016-02-22 03:41
Will get back with you as soon as we have time to dig into it. We are customizing the control with CSS. Same CSS on 8.6 works, just changing to 9.x breaks. Everything else is the same.

I have a couple of ideas, will look at it as soon as I can and get back with you.

**Comment by cibernox** [comment] 2016-02-22 10:29
@cah-briangantzler Yes, there was a couple breaking changes in styles in 0.9. Check the readme, should be straightforward to fix, but If you are using sass, I recommend you to style the component using the sass variables to the maximum extent possible.

It will generate less code and will be more resilent to changes in class names (although I don't plan any other change before 1.0)

**Comment by cah-briangantzler** [comment] 2016-03-01 20:43
I have tested with the most current version and it does appear to work as expected without any changes on our part. Do not close the issue yet until I actually implement it.

Thanks

**Comment by cibernox** [comment] 2016-03-01 21:46
Good news then. 
I've a bit overwhelmed this week with regular work si I'm a bit behind with issues and PRs :sweat:

**Comment by cah-briangantzler** [comment] 2016-03-08 20:26
This appears fixed in the 0.9.0

Thanks for the help

**Closed** 2016-03-08 20:27 UTC
