### ISSUE TITLE
Uncaught Error: Assertion Failed: {{ember-power-select}} requires an `onchange`

### ISSUE THREAD

**Issue by ericop** [cibernox/ember-power-select#60] opened 2015-10-22 19:46 UTC
So I'm just following the example
### Template

     {{#ember-power-select selected=destination options=cities onchange=(action "chooseDestination") as |name|}}
        {{name}}
     {{/ember-power-select}}

### JS
    import Ember from 'ember';

    export default Ember.Controller.extend({
      cities: ['Barcelona', 'London', 'New York', 'Porto'],
      destination: 'London',

      actions: {
        chooseDestination(city) {
          this.set('destination', city);
          console.log('!!!!!!!!!', this.get('destination'));
        }
      }
    });

## Error when I go to the route
        Uncaught Error: Assertion Failed: {{ember-power-select}} requires an `onchange` function_emberMetalCore.default.assert @ ember.debug.js:5342didInitAttrs @ ember-power-select.js:32_emberRuntimeSystemObject.default.extend.trigger @ ember.debug.js:47356superWrapper @ ember.debug.js:22381Renderer.componentInitAttrs @ ember.debug.js:12210_emberViewsViewsCore_view.default.extend.init @ ember.debug.js:49793superWrapper @ ember.debug.js:22377superFunction @ ember.debug.js:17850_emberViewsViewsView.default.extend.init @ ember.debug.js:46668superWrapper @ ember.debug.js:22377Class @ ember.debug.js:37284ClassMixinProps.create @ ember.debug.js:37720(anonymous function) @ ember.debug.js:10014createComponent @ ember.debug.js:10031ComponentNodeManager.create @ ember.debug.js:9771componentHook @ ember.debug.js:7953handleRedirect @ ember.debug.js:51003block @ ember.debug.js:50975_htmlbarsUtilObjectUtils.merge.block @ ember.debug.js:50206RenderResult.populateNodes @ ember.debug.js:51871RenderResult.render @ ember.debug.js:51808render @ ember.debug.js:51627(anonymous function) @ ember.debug.js:52417renderAndCleanup @ ember.debug.js:52454block @ ember.debug.js:52415(anonymous function) @ ember.debug.js:10193instrument @ ember.debug.js:10719ViewNodeManager.render @ ember.debug.js:10180exports.default.render @ ember.debug.js:9285handleKeyword @ ember.debug.js:51067keyword @ ember.debug.js:51192exports.default @ ember.debug.js:9147handleKeyword @ ember.debug.js:51028handleRedirect @ ember.debug.js:51014inline @ ember.debug.js:51157_htmlbarsUtilObjectUtils.merge.content @ ember.debug.js:50227RenderResult.populateNodes @ ember.debug.js:51875RenderResult.render @ ember.debug.js:51808render @ ember.debug.js:51627(anonymous function) @ ember.debug.js:52417renderAndCleanup @ ember.debug.js:52454block @ ember.debug.js:52415keywords.yield @ ember.debug.js:51238handleKeyword @ ember.debug.js:51028handleRedirect @ ember.debug.js:51014inline @ ember.debug.js:51157_htmlbarsUtilObjectUtils.merge.content @ ember.debug.js:50227RenderResult.populateNodes @ ember.debug.js:51875RenderResult.render @ ember.debug.js:51808render @ ember.debug.js:51627(anonymous function) @ ember.debug.js:52417renderAndCleanup @ ember.debug.js:52454block @ ember.debug.js:52415keywords.yield @ ember.debug.js:51238handleKeyword @ ember.debug.js:51028handleRedirect @ ember.debug.js:51014inline @ ember.debug.js:51157_htmlbarsUtilObjectUtils.merge.content @ ember.debug.js:50227RenderResult.populateNodes @ ember.debug.js:51875RenderResult.render @ ember.debug.js:51808render @ ember.debug.js:51627(anonymous function) @ ember.debug.js:52417renderAndCleanup @ ember.debug.js:52454block @ ember.debug.js:52415(anonymous function) @ ember.debug.js:9915instrument @ ember.debug.js:10719ComponentNodeManager.render @ ember.debug.js:9908componentHook @ ember.debug.js:7965handleRedirect @ ember.debug.js:51003block @ ember.debug.js:50975_htmlbarsUtilObjectUtils.merge.block @ ember.debug.js:50206RenderResult.populateNodes @ ember.debug.js:51871RenderResult.render @ ember.debug.js:51808render @ ember.debug.js:51627(anonymous function) @ ember.debug.js:52417renderAndCleanup @ ember.debug.js:52454block @ ember.debug.js:52415keywords.yield @ ember.debug.js:51238handleKeyword @ ember.debug.js:51028handleRedirect @ ember.debug.js:51014inline @ ember.debug.js:51157_htmlbarsUtilObjectUtils.merge.content @ ember.debug.js:50227RenderResult.populateNodes @ ember.debug.js:51875RenderResult.render @ ember.debug.js:51808render @ ember.debug.js:51627(anonymous function) @ ember.debug.js:52417renderAndCleanup @ ember.debug.js:52454block @ ember.debug.js:52415(anonymous function) @ ember.debug.js:10193instrument @ ember.debug.js:10719ViewNodeManager.render @ ember.debug.js:10180exports.default.render @ ember.debug.js:9285handleKeyword @ ember.debug.js:51067keyword @ ember.debug.js:51192exports.default @ ember.debug.js:9147handleKeyword @ ember.debug.js:51028handleRedirect @ ember.debug.js:51014inline @ ember.debug.js:51157_htmlbarsUtilObjectUtils.merge.content @ ember.debug.js:50227RenderResult.populateNodes @ ember.debug.js:51875RenderResult.render @ ember.debug.js:51808render @ ember.debug.js:51627(anonymous function) @ ember.debug.js:52417renderAndCleanup @ ember.debug.js:52454block @ ember.debug.js:52415(anonymous function) @ ember.debug.js:10193instrument @ ember.debug.js:10719ViewNodeManager.render @ ember.debug.js:10180renderHTMLBarsBlock @ ember.debug.js:10985_emberMetalMixin.Mixin.create.renderBlock @ ember.debug.js:44326Renderer_prerenderTopLevelView @ ember.debug.js:12105Renderer_renderTopLevelView @ ember.debug.js:12114Queue.invoke @ ember.debug.js:908Queue.flush @ ember.debug.js:974DeferredActionQueues.flush @ ember.debug.js:770Backburner.end @ ember.debug.js:160Backburner.run @ ember.debug.js:228Backburner.join @ ember.debug.js:263run.join @ ember.debug.js:20280run.bind @ ember.debug.js:20343jQuery.Callbacks.fire @ jquery.js:3148jQuery.Callbacks.self.fireWith @ jquery.js:3260jQuery.extend.ready @ jquery.js:3472completed @ jquery.js:3503

**Comment by cibernox** [comment] 2015-10-22 21:39
The code looks fine, and the code I know for sure that works because the example in the docs is a live example.

Perhaps you're in Ember <= 1.13.8?

**Comment by ericop** [comment] 2015-10-23 14:07
The project I tried it out on was https://github.com/ericop/pizza-ember-spring-boot , which is 1.13.8 CLI, which defaults to 1.13.7 for Ember and 1.13.8 for Ember Data.

**Comment by cibernox** [comment] 2015-10-23 14:41
That is a known issue then. Actually is not a bug in the addon but a bug in Ember 1.13.8 and older that was fixed in 1.13.9.

From the readme:

> Ember Power Select works in Ember 1.13.9+ or 2.0+, including beta and canary, with no deprecations whatsoever.

Perhaps I should warn in red or something to make it more visible.

**Comment by cibernox** [comment] 2015-10-23 14:42
Thanks for reporting anyway :+1:

**Closed by cibernox** 2015-10-23 14:42 UTC
