### ISSUE TITLE
Cannot read property 'offsetTop' of null

### ISSUE THREAD

**Issue by rhyek** [cibernox/ember-power-select#642] opened 2016-08-21 03:47 UTC
Using Ember 2.7 and ember-power-select 1.0.0-beta.12, I have two basic selects set up like this:
```hbs
{{#power-select
  selected=vendor.country
  options=countries
  searchField='name'
  onchange=(action 'chooseCountry' vendor)
  as |country|
}}
  {{country.name}}
{{/power-select}}

{{#power-select
  selected=vendor.state
  options=states
  searchField='name'
  onchange=(action (mut vendor.state))
  as |state|
}}
  {{state.name}}
{{/power-select}}
```
I'll click on one, the options list opens, then, without closing it, I'll click on the other select, get the mentioned error in console while the other options list opens, and I'll get a `Cannot read property 'offsetTop' of null` error in console. After this, I can't close the second options list no matter what I try and basically both selects are unusable (also unable to select items).

I tried to set up a demo of this on `ember-twiddle`, but I'm not sure it supports addons quite yet.

**Comment by jlevycpa** [comment] 2016-08-24 21:01
I can confirm that I am seeing the same behavior on 1.0.0-beta.13.

**Comment by michalsnik** [comment] 2016-08-26 11:29
+1 there is definitely an issue with this one

**Comment by cibernox** [comment] 2016-08-26 12:40
Ok, time to check this

**Comment by cibernox** [comment] 2016-08-26 13:32
In theory ember-twiddle should work, but there is an issue with addons in 2.7.

I tried to reproduce it but I couldn't. Any other indication (or dummy app that presents this behaviour) would help.

**Comment by michalsnik** [comment] 2016-08-26 15:47
@cibernox I reproduced this bag and created simple repository for this:
https://github.com/michalsnik/ember-power-select-issue-642

Feel free to check it out.

Basically the issue appears when you open a select that doesn't have any items inside and without closing it open another select.

cc @rhyek

**Comment by michalsnik** [comment] 2016-08-26 16:20
I know exactly what causes issue now:
When one of the dropdown has selected element which index is bigger than number of items in other select component, when you open the "smaller" select and without closing it try to open the one that has already selected element with bigger index - it crashes.

It looks like the function `scrollTo` is looking for an element on opened list with index that is already selected on other select component. At least it looks like so.

I'm trying to find a proper solution now.

**Comment by cibernox** [comment] 2016-08-28 18:17
Ok, with this last commit I can reproduce it!

**Closed** 2016-08-28 19:25 UTC
